Sparse dvr
Schoyen/quantum-systems pull request #38
Opened 2020-03-18 10:34 UTC by halvarsu

Use the library [sparse](https://sparse.pydata.org/en/latest/index.html) to represent the sparse u-matrix elements. Since `sparse` does not yet have an einsum-implementation, all `einsum`-calls have to be rewritten to `tensordot` if this is going to work. Is this a feasible and/or desirable task?

2020-09-18 08:10 UTC, Schoyen requested changes
This looks good all in all. There's only a few small comments, and maybe we need to discuss the handling of the spin-squared operator for DVR?

2020-09-18 08:10 UTC, Schoyen commented on quantum_systems/sinc_dvr/one_dim/sinc_dvr.py
>          super().change_basis(*args, **kwargs)
This method looks redundant :P

2020-09-18 08:25 UTC, Schoyen commented
Hmm, come to think of it, you need to merge with master first. This pull request looks to be a little behind.

2020-09-18 13:47 UTC, halvarsu commented on quantum_systems/quantum_dots/one_dim/one_dim_potentials.py
> +
Ah yes of course. This was done in the Northug-part of my master:-)

2020-09-18 13:48 UTC, halvarsu commented on quantum_systems/sinc_dvr/one_dim/sinc_dvr.py
>  from ... import BasisSet
yup. You are right, that is better with regards to pep 8 as well

2020-09-18 13:56 UTC, halvarsu commented on quantum_systems/sinc_dvr/one_dim/sinc_dvr.py
> +            self.set_u_repr("4d")
Makes sense, but we would have to set a limit for what "large" constitutes. Maybe `l > 100`, as this gives `size(u) = 1.6 GB` for complex-valued matrix elements?

2020-09-18 14:47 UTC, halvarsu commented
Huh, doesn't github show merge-commits from master?

2020-09-21 09:03 UTC, Schoyen commented on quantum_systems/quantum_dots/one_dim/one_dim_potentials.py
> +
![](https://media.giphy.com/media/13GIgrGdslD9oQ/giphy.gif)

2020-09-21 10:36 UTC, Schoyen commented on quantum_systems/sinc_dvr/one_dim/sinc_dvr.py
>          super().change_basis(*args, **kwargs)
Ah, I didn't see the line below :P

2020-09-21 10:36 UTC, Schoyen approved these changes

2020-09-21 10:37 UTC, Schoyen commented
Lets do the merge! :champagne:

2020-09-21 10:57 UTC, merged